site_name: Curiosity's Handbook
site_url: https://ttrpg-handbook.kalvin.live

nav:
  - Using this Guide: index.md
  - General Rules: general-rules.md
  - Adventure and Combat: adventure-and-combat.md
  - Create a Character: create-a-character.md
  - Races:
    - Changeling: races/changeling.md
    - Dwarf: races/dwarf.md
    - Elf: races/elf.md
    - Gnome: races/gnome.md
    - Hin: races/hin.md
    - Human: races/human.md
    - Interling: races/interling.md
    - Orc: races/orc.md
    - Planetouched: races/planetouched.md
  - Classes:
    - classes/index.md
    - Artificer:
      - classes/artificer/index.md
      - Alchemist: classes/artificer/alchemist.md
      - Armorer: classes/artificer/armorer.md
      - Artillerist: classes/artificer/artillerist.md
      - Battle Smith: classes/artificer/battle-smith.md
    - Barbarian:
      - classes/barbarian/index.md
    - Bard:
      - classes/bard/index.md
    - Cleric:
      - classes/cleric/index.md
    - Druid:
      - classes/druid/index.md
    - Fighter:
      - classes/fighter/index.md
    - Monk:
      - classes/monk/index.md
    - Paladin:
      - classes/paladin/index.md
    - Ranger:
      - classes/ranger/index.md
    - Rogue:
      - classes/rogue/index.md
    - Sorcerer:
      - classes/sorcerer/index.md
    - Warlock:
      - classes/warlock/index.md
    - Wizard:
      - classes/wizard/index.md
  - Feats: feats.md
  - Spells: spells.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - content.tooltips

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - __scripts__/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search