name: setup-python
description: "Setup Python and install dependencies for the project."
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
