name: publish-to-github-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: ./.github/workflows/setup-python

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with: 
          static_site_generator: mkdocs

      - name: Build
        run:  mkdocs build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v4